In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env=gym.make("FrozenLake-v0")
env

<TimeLimit<FrozenLakeEnv<FrozenLake-v0>>>

In [5]:
#Get size of action space
action_space_size=env.action_space.n
#Get size of state space
state_space_size=env.observation_space.n
print(action_space_size)
print(state_space_size)

4
16


In [6]:
q_table=np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
#Number of episodes we want our agent to play during training
num_episodes=10000
#Maximum number of steps our agent will take per episode
max_steps_per_episode=100
#Rate of learning
learning_rate=0.1
#After every move you multiply with the discount rate
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_rate_decay=0.001




In [31]:
rewards_all_episodes=[]
for episode in range(num_episodes):
    state=env.reset()
    done=False
    rewards_current_episode=0
    for step in range(max_steps_per_episode):
        exploration_rate_threshold=random.uniform(0,1)
        if exploration_rate_threshold>exploration_rate:
            action=np.argmax(q_table[state,:])
        else:
            action=env.action_space.sample()
        new_state,reward,done,info=env.step(action)
        q_table[state,action]=q_table[state,action]*(1-learning_rate)+learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))
        state=new_state
        rewards_current_episode+=reward
        if done==True:
            break
    exploration_rate=min_exploration_rate+(max_exploration_rate-min_exploration_rate)*np.exp(-exploration_rate_decay*episode)
    rewards_all_episodes.append(rewards_current_episode)
rewards_per_thousand_episodes=np.split(np.array(rewards_all_episodes),num_episodes/1000)
count=1000
print("Average reward per thousand episodes")
for r in rewards_per_thousand_episodes:
    print(count,":",str(sum(r/1000)))
    count+=1000
print("Q-table")
print(q_table)
    

Average reward per thousand episodes
1000 : 0.5540000000000004
2000 : 0.7490000000000006
3000 : 0.6950000000000005
4000 : 0.7120000000000005
5000 : 0.7380000000000005
6000 : 0.6990000000000005
7000 : 0.7530000000000006
8000 : 0.7300000000000005
9000 : 0.7520000000000006
10000 : 0.7180000000000005
Q-table
[[0.51317656 0.49647997 0.49335469 0.49761426]
 [0.39705743 0.38998434 0.38971983 0.50730154]
 [0.39116715 0.40275521 0.39921477 0.48657679]
 [0.38268027 0.37750552 0.35471513 0.47551231]
 [0.52343457 0.44472972 0.420905   0.34523324]
 [0.         0.         0.         0.        ]
 [0.43947236 0.13374941 0.19844451 0.15180746]
 [0.         0.         0.         0.        ]
 [0.42993687 0.4685595  0.416894   0.55145862]
 [0.39724855 0.59457514 0.26942315 0.41976442]
 [0.58854271 0.39331    0.38414108 0.34352627]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.53694028 0.40560991 0.6794765  0.55836132]
 [0.72164088 0.86208412 0.70482226 0

In [33]:
for episode in range(5):
    state=env.reset()
    done=False
    print("Episode number:",episode+1)
    time.sleep(1)
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action=np.argmax(q_table[state,:])
        new_state,reward,done,info=env.step(action)
        if done:
            clear_output(wait=True)
            env.render()
            if reward==1:
                print("Wohooo!!You have reached your goal")
                time.sleep(3)
            else:
                print("Oops!!You fell in the hole")
                time.sleep(3)
            clear_output(wait=True)
            break
        state=new_state
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
Oops!!You fell in the hole
